### ISSUE TITLE
sql?

### ISSUE THREAD

**Issue by MagicFox** [imzyf/maven-mybatis-spring-springMVC#1]
where is the table sql?

**Comment by imzyf** [comment]
DROP TABLE IF EXISTS `info`;
CREATE TABLE `info` (
  `id` bigint(11) NOT NULL AUTO_INCREMENT,
  `key` varchar(45) DEFAULT NULL,
  `value` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

INSERT INTO `info` VALUES ('1', '22', 'fff');

**Comment by imzyf** [comment]
```
DROP TABLE IF EXISTS `info`;
CREATE TABLE `info` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `key` varchar(45) DEFAULT NULL,
  `value` varchar(45) DEFAULT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;

-- ----------------------------
-- Records of info
-- ----------------------------
INSERT INTO `info` VALUES ('1', '22', 'fff');
```
